-- Alpha Postgres owner split Phase 3A rollback
-- Generated by scripts/postgres_owner_plan.py.
-- Catalog source: ssh:jarvisbrain@jarvis-brain.tail40ed36.ts.net.
--
-- Restores Phase 3A ownership prep back to jarvisbrain.
-- Does not drop roles until ownership is restored.

\set ON_ERROR_STOP on

BEGIN;

ALTER ROLE jarvisbrain SUPERUSER NOBYPASSRLS CREATEDB CREATEROLE;

ALTER DATABASE jarvis_alpha OWNER TO jarvisbrain;
ALTER TABLE public.alpha_agent_events OWNER TO jarvisbrain;
ALTER TABLE public.alpha_agent_runs OWNER TO jarvisbrain;
ALTER TABLE public.alpha_agents OWNER TO jarvisbrain;
ALTER TABLE public.alpha_approval_audit OWNER TO jarvisbrain;
ALTER TABLE public.alpha_approval_audit_quarantine OWNER TO jarvisbrain;
ALTER TABLE public.alpha_approval_queue OWNER TO jarvisbrain;
ALTER VIEW public.alpha_audit_stream OWNER TO jarvisbrain;
ALTER TABLE public.alpha_briefings OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_briefings_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_buddy_events OWNER TO jarvisbrain;
ALTER TABLE public.alpha_budget_config OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_budget_config_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_cloud_costs OWNER TO jarvisbrain;
ALTER TABLE public.alpha_conversation_memory OWNER TO jarvisbrain;
ALTER TABLE public.alpha_credit_balance OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_credit_balance_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_allowed_paths OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_dream_allowed_paths_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_blocked_writes OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_dream_blocked_writes_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_cost_caps OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_cost_counters OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_dream_cost_counters_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_model_policy OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_sessions OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_dream_sessions_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_dream_steps OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_dream_steps_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_gmail_oauth_health OWNER TO jarvisbrain;
ALTER TABLE public.alpha_hardware_config OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_hardware_config_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_honeypot_events OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_honeypot_events_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_message_body_vault OWNER TO jarvisbrain;
ALTER TABLE public.alpha_model_pricing OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_model_pricing_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_node_registry OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_node_registry_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_overnight_approvals OWNER TO jarvisbrain;
ALTER TABLE public.alpha_perplexity_credit OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_perplexity_credit_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_power_config OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_power_config_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_power_daily OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_power_daily_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_power_hourly OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_power_hourly_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_power_readings OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_power_readings_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_profiles OWNER TO jarvisbrain;
ALTER TABLE public.alpha_projects OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_projects_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_prompt_registry OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_prompt_registry_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_school_action_candidates OWNER TO jarvisbrain;
ALTER TABLE public.alpha_school_email_messages OWNER TO jarvisbrain;
ALTER TABLE public.alpha_school_email_scan_runs OWNER TO jarvisbrain;
ALTER TABLE public.alpha_school_event_candidates OWNER TO jarvisbrain;
ALTER TABLE public.alpha_secret_rotations OWNER TO jarvisbrain;
ALTER SEQUENCE public.alpha_secret_rotations_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.alpha_semantic_memory OWNER TO jarvisbrain;
ALTER TABLE public.alpha_skill_registry OWNER TO jarvisbrain;
ALTER TABLE public.alpha_subscriptions OWNER TO jarvisbrain;
ALTER TABLE public.alpha_system_flags OWNER TO jarvisbrain;
ALTER TABLE public.alpha_task_events OWNER TO jarvisbrain;
ALTER TABLE public.alpha_task_graphs OWNER TO jarvisbrain;
ALTER TABLE public.alpha_task_steps OWNER TO jarvisbrain;
ALTER TABLE public.alpha_users OWNER TO jarvisbrain;
ALTER TABLE public.alpha_watchdog_events OWNER TO jarvisbrain;
ALTER TABLE public.alpha_workspace_users OWNER TO jarvisbrain;
ALTER TABLE public.alpha_workspaces OWNER TO jarvisbrain;
ALTER TABLE public.chat_messages OWNER TO jarvisbrain;
ALTER TABLE public.chat_threads OWNER TO jarvisbrain;
ALTER TABLE public.jarvis_request_log OWNER TO jarvisbrain;
ALTER TABLE public.pipeline_lessons OWNER TO jarvisbrain;
ALTER SEQUENCE public.pipeline_lessons_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.pipeline_metrics_brain OWNER TO jarvisbrain;
ALTER SEQUENCE public.pipeline_metrics_brain_id_seq OWNER TO jarvisbrain;
ALTER TABLE public.pipeline_trust_scores OWNER TO jarvisbrain;
ALTER TABLE public.schema_migrations OWNER TO jarvisbrain;
ALTER TABLE public.secret_access_log OWNER TO jarvisbrain;
ALTER SEQUENCE public.secret_access_log_id_seq OWNER TO jarvisbrain;
ALTER VIEW public.v_audit_approval OWNER TO jarvisbrain;
ALTER VIEW public.v_audit_cloud_costs OWNER TO jarvisbrain;
ALTER VIEW public.v_audit_tasks OWNER TO jarvisbrain;
ALTER VIEW public.v_audit_watchdog OWNER TO jarvisbrain;
ALTER VIEW public.v_secret_rotation_status OWNER TO jarvisbrain;
ALTER TABLE public.vault_access_log OWNER TO jarvisbrain;
ALTER TABLE public.vault_chunks OWNER TO jarvisbrain;
ALTER TABLE public.vault_document_permissions OWNER TO jarvisbrain;
ALTER TABLE public.vault_documents OWNER TO jarvisbrain;
ALTER TABLE public.vault_pipeline OWNER TO jarvisbrain;
ALTER FUNCTION public.enforce_child_step_tier() OWNER TO jarvisbrain;
ALTER FUNCTION public.rating_allowed(row_rating text, max_rating text) OWNER TO jarvisbrain;
ALTER FUNCTION public.rating_level(r text) OWNER TO jarvisbrain;
ALTER FUNCTION public.update_task_timestamp() OWNER TO jarvisbrain;

REVOKE jarvis_alpha_owner FROM jarvis_alpha_migrator;
DROP ROLE IF EXISTS jarvis_alpha_migrator;
DROP ROLE IF EXISTS jarvis_alpha_owner;

COMMIT;
