-- Alpha Postgres owner split Phase 3B SECURITY DEFINER apply
-- Generated by scripts/postgres_owner_plan.py.
-- Catalog source: ssh:jarvisbrain@jarvis-brain.tail40ed36.ts.net.
--
-- Moves canary-passing SECURITY DEFINER functions to jarvis_alpha_owner.
-- Extension-owned pgaudit C event triggers are excluded by the catalog query.
-- This file does not demote jarvisbrain.

\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jarvis_alpha_owner') THEN
    RAISE EXCEPTION 'Missing owner role: jarvis_alpha_owner';
  END IF;

  IF NOT EXISTS (
      SELECT 1 FROM pg_roles
      WHERE rolname = 'jarvisbrain' AND rolsuper AND NOT rolbypassrls
  ) THEN
    RAISE EXCEPTION 'jarvisbrain is not in expected pre-Phase 3B state';
  END IF;
END
$$;

-- Canary-passing SECURITY DEFINER ownership transfer.
ALTER FUNCTION public.bump_memory_access(p_ids uuid[]) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.cap_episodic_memory(p_user_id text, p_max_rows integer) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.cap_semantic_memory(p_user_id text, p_max_rows integer) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.claim_agent_due_run(p_agent_id text, p_interval_seconds integer) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.consume_approved_queue_item(p_queue_id uuid) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.decide_approval(p_queue_id uuid, p_decision text, p_decided_by text, p_nonce text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.enqueue_approval_request(p_action_classes text[], p_risk_tier text, p_actor_sub text, p_actor_type text, p_description text, p_parameters_hash text, p_nonce text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.enqueue_dream_step_approval_request(p_action_classes text[], p_risk_tier text, p_actor_sub text, p_actor_type text, p_description text, p_parameters_hash text, p_parameters_preview text, p_nonce text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.evict_episodic_memory_older_than(p_user_id text, p_days integer) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.evict_expired_working_memory() OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.expire_orphan_approved_rows() OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.expire_pending_approvals() OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.finish_agent_run(p_run_id uuid, p_status text, p_cost_usd numeric, p_error_text text, p_metadata jsonb) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.forget_memory_by_topic(p_user_id text, p_topic text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.forget_working_memory(p_user_id text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.get_buddy_promotion_candidates(p_user_id text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.list_active_memory_users() OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.mark_agent_event_notification(p_event_id uuid, p_status text, p_result jsonb, p_error text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.record_agent_event(p_agent_id text, p_event_type text, p_title text, p_message text, p_severity text, p_payload jsonb, p_run_id uuid, p_correlation_id text, p_channel_key text, p_notification_status text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.record_buddy_event(p_user_id text, p_event_type text, p_title text, p_body text, p_priority integer, p_source text, p_payload jsonb) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.record_secret_access(p_key_name text, p_source text, p_accessed_at timestamp with time zone, p_node text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.record_watchdog_event(p_service_name text, p_node text, p_event_type text, p_previous_state text, p_current_state text, p_consecutive_failures integer, p_latency_ms numeric, p_http_status integer, p_error_message text, p_action_taken text, p_trace_id uuid) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.run_buddy_memory_maintenance(p_user_id text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.save_semantic_memory(p_user_id uuid, p_fact text, p_category text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.start_agent_run(p_agent_id text, p_trigger_type text, p_trace_id text, p_metadata jsonb) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.store_conversation_memory(p_user_id text, p_session_id text, p_role text, p_summary text, p_embedding vector, p_tier text, p_persistent boolean, p_importance double precision) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.store_message_body_vault(p_channel text, p_external_account text, p_external_message_id text, p_external_thread_id text, p_body_plaintext text, p_summary text, p_body_key text, p_retention_expires_at timestamp with time zone) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.sync_profile_to_user() OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.update_agent_runtime_metadata(p_agent_id text, p_metadata jsonb) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.upsert_dream_agent_run(p_session_id bigint) OWNER TO jarvis_alpha_owner;

COMMIT;

-- Post-change verification.
SELECT pg_get_userbyid(p.proowner) AS owner, count(*)
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE p.prosecdef
  AND n.nspname = 'public'
GROUP BY 1
ORDER BY 1;
