-- Alpha Postgres owner split Phase 3A apply plan
-- Generated by scripts/postgres_owner_plan.py.
-- Catalog source: ssh:jarvisbrain@jarvis-brain.tail40ed36.ts.net.
--
-- Phase 3A executes only role bootstrap and non-SECURITY-DEFINER ownership prep.
-- SECURITY DEFINER transfers and jarvisbrain demotion remain commented pending canaries.
--
-- Required operator gates before running:
-- 1. PR #239 reviewed and merged.
-- 2. Fresh Brain backup completed.
-- 3. Alpha health/readiness green immediately before apply.
-- 4. SECURITY DEFINER canary plan reviewed for Phase 3B.

\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM pg_roles
      WHERE rolname <> 'jarvisbrain' AND rolsuper
  ) THEN
    RAISE EXCEPTION 'Refusing owner split: no non-jarvisbrain superuser recovery role exists';
  END IF;

  IF NOT EXISTS (
      SELECT 1 FROM pg_roles
      WHERE rolname = 'jarvisbrain' AND rolsuper AND NOT rolbypassrls
  ) THEN
    RAISE EXCEPTION 'Refusing owner split: jarvisbrain is not in expected pre-Phase 3 state';
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jarvis_alpha_owner') THEN
    CREATE ROLE jarvis_alpha_owner NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jarvis_alpha_migrator') THEN
    CREATE ROLE jarvis_alpha_migrator LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;
  END IF;
END
$$;

GRANT jarvis_alpha_owner TO jarvis_alpha_migrator;

-- Non-SECURITY-DEFINER ownership prep.
ALTER DATABASE jarvis_alpha OWNER TO jarvis_alpha_owner;
ALTER EXTENSION pgaudit OWNER TO jarvis_alpha_owner;
ALTER EXTENSION pgcrypto OWNER TO jarvis_alpha_owner;
ALTER EXTENSION plpgsql OWNER TO jarvis_alpha_owner;
ALTER EXTENSION vector OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_agent_events OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_agent_runs OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_agents OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_approval_audit OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_approval_audit_quarantine OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_approval_queue OWNER TO jarvis_alpha_owner;
ALTER VIEW public.alpha_audit_stream OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_briefings OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_briefings_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_buddy_events OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_budget_config OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_budget_config_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_cloud_costs OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_conversation_memory OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_credit_balance OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_credit_balance_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_allowed_paths OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_dream_allowed_paths_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_blocked_writes OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_dream_blocked_writes_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_cost_caps OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_cost_counters OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_dream_cost_counters_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_model_policy OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_sessions OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_dream_sessions_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_dream_steps OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_dream_steps_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_gmail_oauth_health OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_hardware_config OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_hardware_config_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_honeypot_events OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_honeypot_events_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_message_body_vault OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_model_pricing OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_model_pricing_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_node_registry OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_node_registry_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_overnight_approvals OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_perplexity_credit OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_perplexity_credit_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_power_config OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_power_config_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_power_daily OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_power_daily_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_power_hourly OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_power_hourly_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_power_readings OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_power_readings_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_profiles OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_projects OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_projects_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_prompt_registry OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_prompt_registry_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_school_action_candidates OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_school_email_messages OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_school_email_scan_runs OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_school_event_candidates OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_secret_rotations OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.alpha_secret_rotations_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_semantic_memory OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_skill_registry OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_subscriptions OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_system_flags OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_task_events OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_task_graphs OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_task_steps OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_users OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_watchdog_events OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_workspace_users OWNER TO jarvis_alpha_owner;
ALTER TABLE public.alpha_workspaces OWNER TO jarvis_alpha_owner;
ALTER TABLE public.chat_messages OWNER TO jarvis_alpha_owner;
ALTER TABLE public.chat_threads OWNER TO jarvis_alpha_owner;
ALTER TABLE public.jarvis_request_log OWNER TO jarvis_alpha_owner;
ALTER TABLE public.pipeline_lessons OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.pipeline_lessons_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.pipeline_metrics_brain OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.pipeline_metrics_brain_id_seq OWNER TO jarvis_alpha_owner;
ALTER TABLE public.pipeline_trust_scores OWNER TO jarvis_alpha_owner;
ALTER TABLE public.schema_migrations OWNER TO jarvis_alpha_owner;
ALTER TABLE public.secret_access_log OWNER TO jarvis_alpha_owner;
ALTER SEQUENCE public.secret_access_log_id_seq OWNER TO jarvis_alpha_owner;
ALTER VIEW public.v_audit_approval OWNER TO jarvis_alpha_owner;
ALTER VIEW public.v_audit_cloud_costs OWNER TO jarvis_alpha_owner;
ALTER VIEW public.v_audit_tasks OWNER TO jarvis_alpha_owner;
ALTER VIEW public.v_audit_watchdog OWNER TO jarvis_alpha_owner;
ALTER VIEW public.v_secret_rotation_status OWNER TO jarvis_alpha_owner;
ALTER TABLE public.vault_access_log OWNER TO jarvis_alpha_owner;
ALTER TABLE public.vault_chunks OWNER TO jarvis_alpha_owner;
ALTER TABLE public.vault_document_permissions OWNER TO jarvis_alpha_owner;
ALTER TABLE public.vault_documents OWNER TO jarvis_alpha_owner;
ALTER TABLE public.vault_pipeline OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.enforce_child_step_tier() OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.rating_allowed(row_rating text, max_rating text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.rating_level(r text) OWNER TO jarvis_alpha_owner;
ALTER FUNCTION public.update_task_timestamp() OWNER TO jarvis_alpha_owner;

-- Held for Phase 3B: SECURITY DEFINER ownership changes.
-- ALTER FUNCTION public.bump_memory_access(p_ids uuid[]) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.cap_episodic_memory(p_user_id text, p_max_rows integer) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.cap_semantic_memory(p_user_id text, p_max_rows integer) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.claim_agent_due_run(p_agent_id text, p_interval_seconds integer) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.consume_approved_queue_item(p_queue_id uuid) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.decide_approval(p_queue_id uuid, p_decision text, p_decided_by text, p_nonce text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.enqueue_approval_request(p_action_classes text[], p_risk_tier text, p_actor_sub text, p_actor_type text, p_description text, p_parameters_hash text, p_nonce text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.enqueue_dream_step_approval_request(p_action_classes text[], p_risk_tier text, p_actor_sub text, p_actor_type text, p_description text, p_parameters_hash text, p_parameters_preview text, p_nonce text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.evict_episodic_memory_older_than(p_user_id text, p_days integer) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.evict_expired_working_memory() OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.expire_orphan_approved_rows() OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.expire_pending_approvals() OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.finish_agent_run(p_run_id uuid, p_status text, p_cost_usd numeric, p_error_text text, p_metadata jsonb) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.forget_memory_by_topic(p_user_id text, p_topic text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.forget_working_memory(p_user_id text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.get_buddy_promotion_candidates(p_user_id text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.list_active_memory_users() OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.mark_agent_event_notification(p_event_id uuid, p_status text, p_result jsonb, p_error text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.record_agent_event(p_agent_id text, p_event_type text, p_title text, p_message text, p_severity text, p_payload jsonb, p_run_id uuid, p_correlation_id text, p_channel_key text, p_notification_status text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.record_buddy_event(p_user_id text, p_event_type text, p_title text, p_body text, p_priority integer, p_source text, p_payload jsonb) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.record_secret_access(p_key_name text, p_source text, p_accessed_at timestamp with time zone, p_node text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.record_watchdog_event(p_service_name text, p_node text, p_event_type text, p_previous_state text, p_current_state text, p_consecutive_failures integer, p_latency_ms numeric, p_http_status integer, p_error_message text, p_action_taken text, p_trace_id uuid) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.run_buddy_memory_maintenance(p_user_id text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.save_semantic_memory(p_user_id uuid, p_fact text, p_category text) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.start_agent_run(p_agent_id text, p_trigger_type text, p_trace_id text, p_metadata jsonb) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.store_conversation_memory(p_user_id text, p_session_id text, p_role text, p_summary text, p_embedding vector, p_tier text, p_persistent boolean, p_importance double precision) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.store_message_body_vault(p_channel text, p_external_account text, p_external_message_id text, p_external_thread_id text, p_body_plaintext text, p_summary text, p_body_key text, p_retention_expires_at timestamp with time zone) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.sync_profile_to_user() OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.update_agent_runtime_metadata(p_agent_id text, p_metadata jsonb) OWNER TO jarvis_alpha_owner;
-- ALTER FUNCTION public.upsert_dream_agent_run(p_session_id bigint) OWNER TO jarvis_alpha_owner;

-- Held for Phase 3B: demote jarvisbrain after canaries pass.
-- ALTER ROLE jarvisbrain NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;

COMMIT;

-- Post-change verification.
SELECT rolname, rolsuper, rolbypassrls, rolcreatedb, rolcreaterole, rolcanlogin
FROM pg_roles
WHERE rolname IN ('jarvisbrain', 'jarvis_alpha_owner', 'jarvis_alpha_migrator')
ORDER BY rolname;

SELECT pg_get_userbyid(datdba) AS database_owner
FROM pg_database
WHERE datname = 'jarvis_alpha';

-- Expected Phase 3A counts from source inventory:
-- - database: 1
-- - database_owned_by_jarvisbrain: 1
-- - extension: 4
-- - extension_owned_by_jarvisbrain: 4
-- - function: 34
-- - function_owned_by_jarvisbrain: 34
-- - relation: 92
-- - relation_owned_by_jarvisbrain: 92
-- - role: 5
-- - role_owned_by_jarvisbrain: 1
-- - schema: 1
-- - security_definer_functions: 30
