"""Initial registry catalog for the agents program.

The database migration seeds these same entries as the durable source of truth.
Keeping typed copies here gives tests and future tooling a code-native contract
before dynamic registry editing is introduced.
"""

from __future__ import annotations

from typing import Any

from brain.registry.models import AgentSpec, SkillSpec
from brain.services.internet_scout.source_selection import (
    BEACON_ABILITY_DATA_SOURCE_IDS,
    BEACON_ON_HOLD_DATA_SOURCE_IDS,
)


def _skill_metadata(
    *,
    data_classification: str = "none",
    side_effect_class: str = "read",
    timeout_s: int = 30,
    retry_policy: str = "none",
    rate_limit: str = "default",
    cost_mode: str = "none",
    max_usd_per_call: float = 0.0,
    model_policy: str | None = None,
    egress_mode: str = "none",
    provider: str | None = None,
    data_source_id: str | None = None,
    data_source_ids: list[str] | None = None,
    allowed_hosts: list[str] | None = None,
    compensation: str = "not_applicable",
    test_ref: str = "tests/test_agent_skill_registry.py",
    runbook_ref: str = "docs/JARVIS_Alpha_Skills_Agents_Catalog_v0_9.md",
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the compact Skill Manifest v1 metadata block.

    Provider credentials, URLs, and secret names stay outside the manifest.
    This is governance metadata: risk, egress, runtime, cost, and audit shape.
    """

    egress: dict[str, Any] = {
        "mode": egress_mode,
        "provider": provider,
        "allowed_hosts": allowed_hosts or [],
    }
    if data_source_id is not None:
        egress["data_source_id"] = data_source_id
    if data_source_ids:
        egress["data_source_ids"] = data_source_ids

    metadata: dict[str, Any] = {
        "manifest": {
            "manifest_version": 1,
            "data_classification": data_classification,
            "side_effect_class": side_effect_class,
            "input_schema_ref": "registry://schemas/skill-input/default-v1",
            "output_schema_ref": "registry://schemas/skill-output/default-v1",
            "runtime": {
                "timeout_s": timeout_s,
                "retry_policy": retry_policy,
                "rate_limit": rate_limit,
            },
            "cost": {
                "mode": cost_mode,
                "max_usd_per_call": max_usd_per_call,
                "model_policy": model_policy,
            },
            "egress": egress,
            "audit": {
                "event_name": "skill.invoke",
                "redact_fields": ["token", "secret", "body"],
            },
            "compensation": compensation,
            "test_ref": test_ref,
            "runbook_ref": runbook_ref,
        }
    }
    if extra:
        metadata.update(extra)
    return metadata


INITIAL_SKILLS: tuple[SkillSpec, ...] = (
    SkillSpec(
        name="notify.send",
        domain="notify",
        action="send",
        description="Send an Alpha notification through the primary ChatOps channel.",
        approval_tier="T2",
        scope="notify.send",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="operator_notification",
            timeout_s=10,
            retry_policy="fallback_to_pushover",
            rate_limit="60/minute/system",
            egress_mode="gateway",
            provider="mattermost",
            compensation="send_followup_correction",
            test_ref="tests/test_notify_skill.py",
            extra={
                "primary": "mattermost",
                "delivery": "incoming_webhook",
                "fallback": "pushover",
            },
        ),
    ),
    SkillSpec(
        name="notify.send_mattermost",
        domain="notify",
        action="send_mattermost",
        description="Send a Mattermost ChatOps notification through Gateway.",
        approval_tier="T2",
        scope="notify.send",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="operator_notification",
            timeout_s=10,
            retry_policy="none",
            rate_limit="60/minute/system",
            egress_mode="gateway",
            provider="mattermost",
            compensation="send_followup_correction",
            test_ref="tests/test_notify_skill.py",
            extra={
                "egress": "gateway",
                "provider": "mattermost",
                "delivery": "incoming_webhook",
                "rest_api": "phase2",
            },
        ),
    ),
    SkillSpec(
        name="notify.send_pushover",
        domain="notify",
        action="send_pushover",
        description="Send a fallback Pushover notification to Ken through Gateway.",
        approval_tier="T2",
        scope="notify.send",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="operator_notification",
            timeout_s=10,
            retry_policy="none",
            rate_limit="60/minute/system",
            egress_mode="gateway",
            provider="pushover",
            compensation="send_followup_correction",
            test_ref="tests/test_notify_skill.py",
            extra={"egress": "gateway", "provider": "pushover", "role": "fallback"},
        ),
    ),
    SkillSpec(
        name="agent_board.read",
        domain="agent_board",
        action="read",
        description=(
            "Read Alpha Agent Board work items, assignments, and registry summaries."
        ),
        approval_tier="T1",
        scope="agents.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            timeout_s=10,
            rate_limit="60/minute/operator",
            test_ref="tests/test_agent_board.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
            },
        ),
    ),
    SkillSpec(
        name="agent_board.queue_item",
        domain="agent_board",
        action="queue_item",
        description=(
            "Queue an operator-reviewed Alpha Agent Board work item without "
            "executing it."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="30/minute/operator",
            compensation="cancel_work_item",
            test_ref="tests/test_agent_board.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "does_not_execute_agents": True,
            },
        ),
    ),
    SkillSpec(
        name="agent_board.update_status",
        domain="agent_board",
        action="update_status",
        description=(
            "Update Alpha Agent Board status and handoff metadata without "
            "bypassing approvals."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="60/minute/operator",
            compensation="status_change_event_trail",
            test_ref="tests/test_agent_board.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "does_not_execute_agents": True,
            },
        ),
    ),
    SkillSpec(
        name="agent_board.dispatch_item",
        domain="agent_board",
        action="dispatch_item",
        description=(
            "Bridge an approved Agent Board work item into a TaskGraph and wake "
            "the existing executor."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="30/minute/operator",
            compensation="cancel_task_graph_and_work_item",
            test_ref="tests/test_agent_board.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "executor_bridge": "task_graph",
                "approval_gate": "alpha_task_steps.approval_required",
                "wakes_executor": True,
            },
        ),
    ),
    SkillSpec(
        name="agent_board.delegate_item",
        domain="agent_board",
        action="delegate_item",
        description=(
            "Split a governed Agent Board work item into role-specific child "
            "items with isolated context and output contracts."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="30/minute/operator",
            compensation="cancel_delegated_child_items",
            test_ref="tests/test_agent_board.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "delegation_model": "board_child_items",
                "queues_agent_board_items": True,
                "does_not_execute_agents": True,
                "output_contract_required": True,
            },
        ),
    ),
    SkillSpec(
        name="agent_board.dispatch_delegation",
        domain="agent_board",
        action="dispatch_delegation",
        description=(
            "Dispatch delegated child Agent Board work items into TaskGraphs and "
            "record parent roll-up metadata."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="20/minute/operator",
            compensation="cancel_child_task_graphs_and_parent_work_item",
            test_ref="tests/test_agent_board.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "delegation_model": "board_child_items",
                "executor_bridge": "task_graph",
                "approval_gate": "alpha_task_steps.approval_required",
                "wakes_executor": True,
                "rolls_up_to_parent": True,
            },
        ),
    ),
    SkillSpec(
        name="agent_schedule.read",
        domain="agent_schedule",
        action="read",
        description=(
            "Read governed Agent Board scheduled work definitions and run history."
        ),
        approval_tier="T1",
        scope="agents.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            timeout_s=10,
            rate_limit="60/minute/operator",
            test_ref="tests/test_agent_schedules.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
            },
        ),
    ),
    SkillSpec(
        name="agent_schedule.create",
        domain="agent_schedule",
        action="create",
        description=(
            "Create or update governed scheduled work that later queues Agent "
            "Board items."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="30/minute/operator",
            compensation="cancel_schedule",
            test_ref="tests/test_agent_schedules.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "does_not_execute_agents": True,
            },
        ),
    ),
    SkillSpec(
        name="agent_schedule.materialize_due",
        domain="agent_schedule",
        action="materialize_due",
        description=(
            "Materialize due scheduled work into queued Agent Board items "
            "without dispatching execution."
        ),
        approval_tier="T2",
        scope="agents.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="12/minute/system",
            compensation="cancel_materialized_work_item",
            test_ref="tests/test_agent_schedules.py",
            extra={
                "execution_path": "fastapi_route",
                "operator_surface": "helm",
                "does_not_execute_agents": True,
                "scheduler_path": "launchagent",
                "queues_agent_board_items": True,
            },
        ),
    ),
    SkillSpec(
        name="unifi.wan_status",
        domain="unifi",
        action="wan_status",
        description="Read WAN status, speed, latency, and ISP state.",
        approval_tier="T1",
        scope="network.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="security",
            egress_mode="gateway",
            provider="unifi",
            rate_limit="30/minute/agent",
            test_ref="tests/test_agent_runtime_network.py",
        ),
    ),
    SkillSpec(
        name="unifi.clients",
        domain="unifi",
        action="clients",
        description="List connected UniFi clients.",
        approval_tier="T1",
        scope="network.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="security",
            egress_mode="gateway",
            provider="unifi",
            rate_limit="30/minute/agent",
            test_ref="tests/test_agent_runtime_network.py",
        ),
    ),
    SkillSpec(
        name="unifi.health_check",
        domain="unifi",
        action="health_check",
        description="Read controller, AP, and switch health signals.",
        approval_tier="T1",
        scope="network.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="security",
            egress_mode="gateway",
            provider="unifi",
            rate_limit="30/minute/agent",
            test_ref="tests/test_agent_runtime_network.py",
            extra={"adapter": "gateway_unifi"},
        ),
    ),
    SkillSpec(
        name="unifi.daughters_screentime",
        domain="unifi",
        action="daughters_screentime",
        description="Pause or resume daughters' registered devices on the home network.",
        approval_tier="T4",
        scope="network.screentime",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="child",
            side_effect_class="physical_world",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/child",
            egress_mode="gateway",
            provider="unifi",
            compensation="restore_previous_network_state",
            test_ref="tests/test_skill_policy_gate.py",
            extra={"child_profile_block": False},
        ),
    ),
    SkillSpec(
        name="weather.current",
        domain="weather",
        action="current",
        description="Read current weather conditions through Gateway's Open-Meteo adapter.",
        approval_tier="T1",
        scope="weather.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="personal",
            timeout_s=15,
            retry_policy="cache_then_transient_retry",
            rate_limit="30/minute/system",
            egress_mode="gateway",
            provider="open_meteo",
            data_source_id="open-meteo",
            allowed_hosts=["api.open-meteo.com"],
            test_ref="tests/test_weather_skill.py",
            extra={
                "execution_path": "skill_runner",
                "cache_ttl_seconds": 600,
                "location_policy": "configured_home_or_explicit_coordinates",
            },
        ),
    ),
    SkillSpec(
        name="gmail.search_threads",
        domain="gmail",
        action="search_threads",
        description="Search Gmail threads across configured accounts.",
        approval_tier="T1",
        scope="email.read",
        metadata=_skill_metadata(
            data_classification="personal",
            timeout_s=20,
            retry_policy="transient_retry",
            rate_limit="60/minute/account",
            egress_mode="gateway",
            provider="gmail",
            test_ref="tests/services/test_gmail_client.py",
        ),
    ),
    SkillSpec(
        name="gmail.read_thread",
        domain="gmail",
        action="read_thread",
        description="Read Gmail thread metadata and allowed body content.",
        approval_tier="T1",
        scope="email.read",
        body_access=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            timeout_s=20,
            retry_policy="transient_retry",
            rate_limit="60/minute/account",
            egress_mode="gateway",
            provider="gmail",
            test_ref="tests/services/test_gmail_client.py",
        ),
    ),
    SkillSpec(
        name="gmail.draft_reply",
        domain="gmail",
        action="draft_reply",
        description="Create a Gmail draft without sending.",
        approval_tier="T2",
        scope="email.write",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="write",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="20/minute/account",
            egress_mode="gateway",
            provider="gmail",
            compensation="delete_or_replace_draft",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="gmail.send",
        domain="gmail",
        action="send",
        description="Send Gmail to non-VIP recipients after approval.",
        approval_tier="T4",
        scope="email.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/operator",
            egress_mode="gateway",
            provider="gmail",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="gmail.send_vip",
        domain="gmail",
        action="send_vip",
        description="Send Gmail to VIP recipients under the encrypted group policy.",
        approval_tier="T1",
        scope="email.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="vip_group_policy",
            egress_mode="gateway",
            provider="gmail",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
            extra={"vip_store": "~/jarvis/.secrets/vip_groups.enc"},
        ),
    ),
    SkillSpec(
        name="imessage.read",
        domain="imessage",
        action="read",
        description="Read recent iMessage thread metadata and allowed body content.",
        approval_tier="T1",
        scope="imessage.read",
        status="active",
        body_access=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            timeout_s=20,
            retry_policy="transient_retry",
            rate_limit="60/minute/bridge",
            egress_mode="local",
            provider="bluebubbles",
            test_ref="tests/services/test_bluebubbles_client.py",
            extra={"body_scope": "imessage.body.read", "adapter": "bluebubbles_local"},
        ),
    ),
    SkillSpec(
        name="imessage.send",
        domain="imessage",
        action="send",
        description="Send iMessage to non-VIP recipients after approval.",
        approval_tier="T4",
        scope="imessage.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/operator",
            egress_mode="tailscale",
            provider="bluebubbles",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="imessage.send_vip",
        domain="imessage",
        action="send_vip",
        description="Send iMessage to VIP recipients under the encrypted group policy.",
        approval_tier="T1",
        scope="imessage.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="vip_group_policy",
            egress_mode="tailscale",
            provider="bluebubbles",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
            extra={"vip_store": "~/jarvis/.secrets/vip_groups.enc"},
        ),
    ),
    SkillSpec(
        name="smarthome.run_trusted_scene",
        domain="smarthome",
        action="run_trusted_scene",
        description="Run a trusted Home Assistant scene from the approved scene list.",
        approval_tier="T1",
        scope="smarthome.scene",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="30/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="run_inverse_scene_or_restore_state",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.run_scene",
        domain="smarthome",
        action="run_scene",
        description="Run an unknown or not-yet-trusted Home Assistant scene after approval.",
        approval_tier="T4",
        scope="smarthome.write",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="run_inverse_scene_or_restore_state",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.set_device",
        domain="smarthome",
        action="set_device",
        description="Set a direct device state through Home Assistant.",
        approval_tier="T4",
        scope="smarthome.write",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="restore_previous_device_state",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.unlock",
        domain="smarthome",
        action="unlock",
        description="Unlock a physical lock through Home Assistant.",
        approval_tier="T5",
        scope="smarthome.security",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="2/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="lock_device_again_and_alert",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.alarm_disarm",
        domain="smarthome",
        action="alarm_disarm",
        description="Disarm a home alarm panel through Home Assistant.",
        approval_tier="T5",
        scope="smarthome.security",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="2/day/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="arm_alarm_again_and_alert",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="tasks.create",
        domain="tasks",
        action="create",
        description="Create an Obsidian Tasks markdown checkbox.",
        approval_tier="T2",
        scope="tasks.write",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="write",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="60/minute/operator",
            egress_mode="local",
            provider="obsidian_tasks",
            compensation="delete_or_mark_created_task_cancelled",
            test_ref="tests/test_obsidian_skills.py",
            extra={
                "execution_path": "skill_runner",
                "config_secret": "OBSIDIAN_VAULT_PATH",  # pragma: allowlist secret
                "default_path_secret": "OBSIDIAN_TASKS_INBOX",  # pragma: allowlist secret
            },
        ),
    ),
    SkillSpec(
        name="notes.search",
        domain="notes",
        action="search",
        description="Search the Obsidian vault.",
        approval_tier="T1",
        scope="notes.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="personal",
            timeout_s=10,
            retry_policy="none",
            rate_limit="120/minute/operator",
            egress_mode="local",
            provider="obsidian",
            test_ref="tests/test_obsidian_skills.py",
            extra={
                "execution_path": "skill_runner",
                "config_secret": "OBSIDIAN_VAULT_PATH",  # pragma: allowlist secret
            },
        ),
    ),
    SkillSpec(
        name="notes.write_private_digest",
        domain="notes",
        action="write_private_digest",
        description="Write an idempotent private digest note into the Obsidian vault.",
        approval_tier="T2",
        scope="notes.write",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="write",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="30/minute/operator",
            egress_mode="local",
            provider="obsidian",
            compensation="delete_created_digest_note",
            test_ref="tests/test_obsidian_skills.py",
            extra={
                "execution_path": "skill_runner",
                "config_secret": "OBSIDIAN_VAULT_PATH",  # pragma: allowlist secret
                "default_path": "AT-0/Private Document Digests",
            },
        ),
    ),
    SkillSpec(
        name="chatops.command_read",
        domain="chatops",
        action="command_read",
        description="Handle token-authenticated read-only Mattermost slash commands.",
        approval_tier="T1",
        scope="chatops.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            timeout_s=10,
            retry_policy="none",
            rate_limit="30/minute/operator",
            egress_mode="local",
            provider="mattermost",
            test_ref="tests/test_agent_events_chatops.py",
            extra={
                "surface": "mattermost",
                "write_commands": "blocked",
                "execution_path": "fastapi_route",
            },
        ),
    ),
    SkillSpec(
        name="chatops.agent_board_control",
        domain="chatops",
        action="agent_board_control",
        description=(
            "Handle token-authenticated Mattermost Agent Board queue, status, "
            "and handoff commands."
        ),
        approval_tier="T2",
        scope="chatops.write",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="20/minute/operator",
            egress_mode="local",
            provider="mattermost",
            compensation="status_change_event_trail",
            test_ref="tests/test_agent_events_chatops.py",
            extra={
                "surface": "mattermost",
                "execution_path": "fastapi_route",
                "operator_surface": "chatops",
                "commands": [
                    "board",
                    "board blocked",
                    "board needs-me",
                    "board queue",
                    "board approve-handoff",
                ],
                "does_not_bypass_alpha_gates": True,
            },
        ),
    ),
    SkillSpec(
        name="approval.canary_t4",
        domain="approval",
        action="canary_t4",
        description="No-op T4 canary for proving SkillRunner approval queue replay.",
        approval_tier="T4",
        scope="approval.canary",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=5,
            retry_policy="idempotent_retry_once",
            rate_limit="5/day/operator",
            egress_mode="none",
            provider=None,
            compensation="not_applicable_no_external_side_effect",
            test_ref="tests/test_approval_canary_skill.py",
            extra={
                "execution_path": "skill_runner",
                "approval_queue_bridge": "enabled",
                "canary": True,
            },
        ),
    ),
    SkillSpec(
        name="secrets.rotate",
        domain="secrets",
        action="rotate",
        description="Rotate approved Alpha secrets and service credentials through the Keyturner workflow.",
        approval_tier="T4",
        scope="secrets.rotate",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="control_plane",
            timeout_s=600,
            retry_policy="checkpointed_rollback",
            rate_limit="10/day/operator",
            egress_mode="tailscale",
            provider="alpha_control_plane",
            compensation="restore_previous_secret_and_restart_services",
            test_ref="tests/test_agent_skill_registry.py",
            extra={
                "execution_path": "skill_runner",
                "approval_queue_bridge": "enabled",
                "approval_required": True,
                "actuator": "gateway_rotation_proxy",
                "handled_secret_classes": [
                    "api_key",
                    "service_token",
                    "service_jwt",
                    "admin_pin",
                    "db_password",
                    "oauth_refresh_token",
                    "oauth_client_secret",
                    "cloudflare_api_token",
                    "cloudflare_tunnel_token",
                    "mattermost_token",
                    "webhook_url",
                    "pushover_token",
                ],
            },
        ),
    ),
    SkillSpec(
        name="evidence.package_report",
        domain="evidence",
        action="package_report",
        description="Package security events, access changes, Cloudflare drift, and key rotations into a tamper-evident report.",
        approval_tier="T2",
        scope="evidence.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="idempotent_retry_once",
            rate_limit="10/day/operator",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={
                "owner_agent": "ledger",
                "planned_for": "security_evidence_reports",
                "evidence_sources": [
                    "security_events",
                    "family_access_changes",
                    "cloudflare_access_changes",
                    "key_rotation_history",
                ],
                "tamper_evidence": "hash_chain_planned",
            },
        ),
    ),
    SkillSpec(
        name="dependencies.scan",
        domain="dependencies",
        action="scan",
        description="Summarize dependency and static-security scan findings for Porchlight.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=300,
            retry_policy="none",
            rate_limit="4/day/system",
            egress_mode="gateway",
            provider="github",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "porchlight", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="cloudflare.policy_drift",
        domain="cloudflare",
        action="policy_drift",
        description="Detect Cloudflare Access application and policy drift for Porchlight.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="transient_retry",
            rate_limit="12/day/system",
            egress_mode="gateway",
            provider="cloudflare",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "porchlight", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="github.branch_protection_drift",
        domain="github",
        action="branch_protection_drift",
        description="Detect GitHub branch protection and required-check drift for Porchlight.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="transient_retry",
            rate_limit="12/day/system",
            egress_mode="gateway",
            provider="github",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "porchlight", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="unifi.quarantine_recommendation",
        domain="unifi",
        action="quarantine_recommendation",
        description="Recommend quarantine actions for unknown UniFi devices without mutating network state.",
        approval_tier="T1",
        scope="network.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=60,
            retry_policy="none",
            rate_limit="30/day/system",
            egress_mode="gateway",
            provider="unifi",
            test_ref="tests/test_agent_skill_registry.py",
            extra={
                "owner_agent": "sweep",
                "saved_for_later": True,
            },
        ),
    ),
    SkillSpec(
        name="unifi.firmware_drift",
        domain="unifi",
        action="firmware_drift",
        description="Detect UniFi gateway, switch, and AP firmware drift for Sweep.",
        approval_tier="T1",
        scope="network.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=90,
            retry_policy="transient_retry",
            rate_limit="12/day/system",
            egress_mode="gateway",
            provider="unifi",
            test_ref="tests/test_agent_skill_registry.py",
            extra={
                "owner_agent": "sweep",
                "saved_for_later": True,
            },
        ),
    ),
    SkillSpec(
        name="unifi.wan_failover_health",
        domain="unifi",
        action="wan_failover_health",
        description="Check WAN failover readiness and health for Sweep.",
        approval_tier="T1",
        scope="network.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=90,
            retry_policy="transient_retry",
            rate_limit="12/day/system",
            egress_mode="gateway",
            provider="unifi",
            test_ref="tests/test_agent_skill_registry.py",
            extra={
                "owner_agent": "sweep",
                "saved_for_later": True,
            },
        ),
    ),
    SkillSpec(
        name="keyturner.oauth_health",
        domain="keyturner",
        action="oauth_health",
        description="Check OAuth refresh-token health and expiry risk for Keyturner.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=90,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "keyturner", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="keyturner.rotation_dry_run",
        domain="keyturner",
        action="rotation_dry_run",
        description="Dry-run a credential rotation plan without changing secrets.",
        approval_tier="T2",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="none",
            rate_limit="10/day/operator",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "keyturner", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="keyturner.secrets_forecast",
        domain="keyturner",
        action="secrets_forecast",
        description="Forecast upcoming secret rotation deadlines for Keyturner.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=60,
            retry_policy="none",
            rate_limit="24/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "keyturner", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="tripwire.source_reputation",
        domain="tripwire",
        action="source_reputation",
        description="Enrich Tripwire honeypot sources with local reputation and repeat-offender context.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=60,
            retry_policy="none",
            rate_limit="60/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "tripwire", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="tripwire.probe_clustering",
        domain="tripwire",
        action="probe_clustering",
        description="Cluster repeated scanner probes across Tripwire trap paths.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=60,
            retry_policy="none",
            rate_limit="60/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "tripwire", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="warden.weekly_brief",
        domain="warden",
        action="weekly_brief",
        description="Prepare a weekly Warden security posture brief.",
        approval_tier="T2",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="none",
            rate_limit="2/day/operator",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "warden", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="warden.auto_ticket",
        domain="warden",
        action="auto_ticket",
        description="Create an operator-visible ticket for a Warden security gap.",
        approval_tier="T3",
        scope="tasks.write",
        status="planned",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="write",
            timeout_s=60,
            retry_policy="idempotent_retry_once",
            rate_limit="20/day/system",
            egress_mode="none",
            compensation="close_or_supersede_duplicate_ticket",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "warden", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="warden.owner_routing",
        domain="warden",
        action="owner_routing",
        description="Route a security gap to the correct security agent owner.",
        approval_tier="T2",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=60,
            retry_policy="none",
            rate_limit="60/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "warden", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="sentry.boundary_inventory",
        domain="sentry",
        action="boundary_inventory",
        description="Inventory Alpha, Brain, Family, Financial, Forge, Cloudflare, and Tailscale data boundaries.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=90,
            retry_policy="none",
            rate_limit="24/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "sentry", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="sentry.cross_system_flow_review",
        domain="sentry",
        action="cross_system_flow_review",
        description="Review cross-system data flows for unexpected Family, Alpha, Brain, Forge, or Financial exposure.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "sentry", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="sentry.pii_log_boundary_scan",
        domain="sentry",
        action="pii_log_boundary_scan",
        description="Scan structured logs and agent events for PII, child data, or financial data crossing approved boundaries.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="security",
            timeout_s=120,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "sentry", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="trade_guard.mode_boundary_review",
        domain="trade_guard",
        action="mode_boundary_review",
        description="Review Financial paper/live mode separation and broker environment boundaries without changing trading state.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="financial",
            timeout_s=90,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "trade_guard", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="trade_guard.kill_switch_review",
        domain="trade_guard",
        action="kill_switch_review",
        description="Review Financial kill-switch, halt-signal, and approval-gate health without changing halt state.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="financial",
            timeout_s=90,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "trade_guard", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="trade_guard.order_path_boundary_review",
        domain="trade_guard",
        action="order_path_boundary_review",
        description="Review order-path boundaries for pre-trade approvals, spend caps, and execution isolation without placing orders.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="financial",
            timeout_s=120,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "trade_guard", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="trade_guard.broker_credential_review",
        domain="trade_guard",
        action="broker_credential_review",
        description="Review broker credential exposure posture and rotation evidence without reading secret values or rotating keys.",
        approval_tier="T1",
        scope="security.read",
        status="planned",
        metadata=_skill_metadata(
            data_classification="financial",
            timeout_s=90,
            retry_policy="none",
            rate_limit="12/day/system",
            egress_mode="none",
            test_ref="tests/test_agent_skill_registry.py",
            extra={"owner_agent": "trade_guard", "saved_for_later": True},
        ),
    ),
    SkillSpec(
        name="internet_scout.search",
        domain="internet_scout",
        action="search",
        description="Gather public search evidence through Beacon and Gateway without browser automation.",
        approval_tier="T2",
        scope="internet_scout.research",
        status="active",
        body_access=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            timeout_s=45,
            retry_policy="gateway_provider_fallback",
            rate_limit="60/hour/user",
            cost_mode="cloud",
            max_usd_per_call=0.02,
            model_policy="gateway_search_provider_order",
            egress_mode="gateway",
            provider="beacon",
            data_source_ids=list(BEACON_ABILITY_DATA_SOURCE_IDS),
            test_ref="tests/test_internet_scout_chat_adapter.py",
            runbook_ref="docs/adr/ADR-0019-beacon-internet-scout.md",
            extra={
                "owner_agent": "internet_scout",
                "chat_mode": "web_search",
                "execution_path": "fastapi_route",
                "source_selection": "registry_backed",
                "on_hold_data_source_ids": list(BEACON_ON_HOLD_DATA_SOURCE_IDS),
                "spend_guard": "gateway_provider_allowlist_and_budget_limits",
            },
        ),
    ),
    SkillSpec(
        name="internet_scout.deep_research",
        domain="internet_scout",
        action="deep_research",
        description="Gather higher-scrutiny cited web evidence through Beacon for chat research mode.",
        approval_tier="T3",
        scope="internet_scout.research",
        status="active",
        body_access=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            timeout_s=90,
            retry_policy="gateway_provider_fallback",
            rate_limit="20/hour/user",
            cost_mode="cloud",
            max_usd_per_call=0.10,
            model_policy="gateway_search_provider_order",
            egress_mode="gateway",
            provider="beacon",
            data_source_ids=list(BEACON_ABILITY_DATA_SOURCE_IDS),
            test_ref="tests/test_internet_scout_chat_adapter.py",
            runbook_ref="docs/adr/ADR-0019-beacon-internet-scout.md",
            extra={
                "owner_agent": "internet_scout",
                "chat_mode": "deep_research",
                "browser_use": "approval_queue_only",
                "execution_path": "fastapi_route",
                "source_selection": "registry_backed",
                "on_hold_data_source_ids": list(BEACON_ON_HOLD_DATA_SOURCE_IDS),
                "spend_guard": "gateway_provider_allowlist_and_budget_limits",
            },
        ),
    ),
    SkillSpec(
        name="internet_scout.browser_task",
        domain="internet_scout",
        action="browser_task",
        description="Queue or run exact-match approved Beacon browser tasks through the approval gate.",
        approval_tier="T4",
        scope="internet_scout.browser",
        status="active",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="control_plane",
            timeout_s=120,
            retry_policy="approval_idempotency_key",
            rate_limit="10/hour/user",
            cost_mode="cloud",
            max_usd_per_call=0.20,
            model_policy="no_autonomous_browser_use",
            egress_mode="gateway",
            provider="beacon_browser_runtime",
            compensation="expire_or_cancel_unconsumed_approval",
            test_ref="tests/test_internet_scout_route.py",
            runbook_ref="docs/adr/ADR-0019-beacon-internet-scout.md",
            extra={
                "owner_agent": "internet_scout",
                "approval_required": True,
                "browser_use": "exact_approval_hash_required",
                "execution_path": "fastapi_route",
            },
        ),
    ),
)


INITIAL_AGENTS: tuple[AgentSpec, ...] = (
    AgentSpec(
        agent_id="buddy",
        display_name="Buddy",
        purpose="Maintain memory, surface operational events, and perform low-risk housekeeping.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="60s",
        launch_label="com.jarvis.alpha.buddy",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["memory.write", "buddy.events.write", "notify.send"],
        cost_daily_cap_usd=0.0,
        metadata={"mattermost_channel_key": "alpha_events"},
    ),
    AgentSpec(
        agent_id="dream_mode",
        display_name="Dream Mode",
        purpose="Plan, review, and execute bounded overnight work through Temporal.",
        risk_tier="T4",
        status="active",
        enabled=True,
        cadence="on_demand",
        launch_label="com.jarvis.alpha.temporal.worker",
        allowed_skills=[
            "notes.search",
            "notes.write_private_digest",
            "notify.send",
            "tasks.create",
        ],
        allowed_scopes=[
            "dream.execute",
            "approval.request",
            "notes.read",
            "notes.write",
            "notify.send",
            "tasks.write",
        ],
        cost_daily_cap_usd=1.0,
        approval_policy={"writes": "approval_queue", "allowlist_only": True},
        metadata={"mattermost_channel_key": "alpha_events"},
    ),
    AgentSpec(
        agent_id="approval_triage",
        display_name="Approval Triage",
        purpose="Surface approval queue events and operator decisions into ChatOps.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="event_driven",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["approval.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "blocked"},
        metadata={"mattermost_channel_key": "needs_input"},
    ),
    AgentSpec(
        agent_id="watchdog",
        display_name="Watchdog",
        purpose="Surface infrastructure health degradation and restoration events.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="60s",
        launch_label="com.jarvis.alpha.watchdog",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["notify.send", "watchdog.events.ingest"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "blocked"},
        metadata={"mattermost_channel_key": "alerts"},
    ),
    AgentSpec(
        agent_id="porchlight",
        display_name="Porchlight",
        purpose="Run scheduled security posture sweeps and surface dangerous findings.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="daily",
        launch_label="com.jarvis.alpha.porchlight",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["notify.send", "security.read"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "security_alerts",
            "report_path": "logs/porchlight_security_report.json",
            "manual_run_enabled": True,
            "schedule_interval_seconds": 86400,
            "warden_managed": True,
            "warden_role": "posture_sweep",
            "external_boundary": {
                "protected_hosts_source": "PORCHLIGHT_CLOUDFLARE_EXPECTED_HOSTS",
                "policy_emails_source": "PORCHLIGHT_CLOUDFLARE_EXPECTED_POLICY_EMAILS",
                "forbidden_apps": ["alpha", "brain", "jarvis-brain"],
                "broad_rules_blocked": ["everyone", "email_domain", "bypass"],
            },
            "planned_skills": [
                "dependencies.scan",
                "cloudflare.policy_drift",
                "github.branch_protection_drift",
            ],
        },
    ),
    AgentSpec(
        agent_id="keyturner",
        display_name="Keyturner",
        purpose="Own approved Alpha key and password rotations across existing rotation jobs.",
        risk_tier="T4",
        status="active",
        enabled=True,
        cadence="on_demand",
        allowed_skills=["secrets.rotate", "notify.send"],
        allowed_scopes=["secrets.rotate", "notify.send", "security.read"],
        cost_daily_cap_usd=0.0,
        approval_policy={
            "writes": "approval_required",
            "api_keys": "T3",  # pragma: allowlist secret
            "service_tokens": "T3",
            "db_passwords": "T4",  # pragma: allowlist secret
            "rollback": "required",
        },
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "rotation_config": "scripts/secrets_rotation.json",
            "existing_actuators": [
                "scripts/rotate_secret.py",
                "scripts/rotate_service_token.py",
                "launchagents/com.jarvis.alpha.rotate.*",
            ],
            "porchlight_relationship": "porchlight_detects_keyturner_remediates",
            "warden_managed": True,
            "warden_role": "credential_rotation",
            "planned_skills": [
                "keyturner.oauth_health",
                "keyturner.rotation_dry_run",
                "keyturner.secrets_forecast",
            ],
        },
    ),
    AgentSpec(
        agent_id="warden",
        display_name="Warden",
        purpose="Coordinate Alpha security agents, summarize posture, and route remediation to the right owner.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="continuous",
        allowed_skills=["notify.send"],
        allowed_scopes=["security.read", "agents.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "delegated"},
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "managed_agents": [
                "porchlight",
                "keyturner",
                "sweep",
                "tripwire",
                "ledger",
                "sentry",
                "trade_guard",
            ],
            "agent_roles": {
                "porchlight": "posture_sweep",
                "keyturner": "credential_rotation",
                "sweep": "network_sweep",
                "tripwire": "honeypot_sensor",
                "ledger": "evidence_reporter",
                "sentry": "data_boundary_monitor",
                "trade_guard": "trading_safety_monitor",
            },
            "active_network_hardening": "service_tls_cert_renewal",
            "supervision_interval_seconds": 600,
            "remediation_policy": {
                "T1": "delegate_low_risk_checks",
                "T4_T5": "route_to_owner_with_approval",
            },
            "authority_model": {
                "observe_only": ["porchlight", "ledger", "sentry", "trade_guard"],
                "approval_required": ["keyturner", "sweep"],
                "notification_only": ["tripwire"],
                "no_autonomous_trade_execution": True,
                "financial_remediation": "route_to_trade_guard_then_operator_approval",
                "credential_remediation": "route_to_keyturner_then_operator_approval",
                "data_boundary_remediation": "route_to_sentry_then_operator_approval",
            },
            "capabilities": [
                "weekly_security_brief",
                "owner_routing",
                "auto_ticket_candidates",
            ],
            "planned_skills": [
                "warden.weekly_brief",
                "warden.auto_ticket",
                "warden.owner_routing",
            ],
        },
    ),
    AgentSpec(
        agent_id="ledger",
        display_name="Ledger",
        purpose="Package security evidence, access changes, Cloudflare drift, and key rotations into tamper-evident reports.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="on_demand",
        allowed_skills=["evidence.package_report", "notify.send"],
        allowed_scopes=["security.read", "agents.read", "evidence.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "report_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "warden_managed": True,
            "warden_role": "evidence_reporter",
            "report_mode": "tamper_evident",
            "capabilities": [
                "security_event_packaging",
                "family_access_change_evidence",
                "cloudflare_access_change_evidence",
                "key_rotation_evidence",
                "hash_chained_report_manifest",
            ],
            "evidence_sources": [
                "alpha_agent_events",
                "alpha_agent_runs",
                "cloudflare_access_audit",
                "keyturner_rotation_ledger",
                "family_external_access_changes",
            ],
            "remediation": "evidence_only",
        },
    ),
    AgentSpec(
        agent_id="sentry",
        display_name="Sentry",
        purpose="Monitor cross-system data boundaries so Family, Alpha, Brain, Forge, and Financial data stay in approved zones.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="on_demand",
        allowed_skills=[
            "sentry.boundary_inventory",
            "sentry.cross_system_flow_review",
            "sentry.pii_log_boundary_scan",
            "notify.send",
        ],
        allowed_scopes=[
            "security.read",
            "agents.read",
            "logs.read",
            "evidence.read",
            "notify.send",
        ],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "warden_managed": True,
            "warden_role": "data_boundary_monitor",
            "monitors": [
                "family_external_boundary",
                "alpha_financial_boundary",
                "brain_data_boundary",
                "forge_code_boundary",
                "pii_log_boundary",
                "cloudflare_access_boundary",
                "tailscale_acl_boundary",
            ],
            "protected_domains": [
                "family",
                "alpha",
                "brain",
                "forge",
                "financial",
            ],
            "capabilities": [
                "boundary_inventory",
                "cross_system_flow_review",
                "pii_log_boundary_scan",
            ],
            "planned_skills": [
                "sentry.boundary_inventory",
                "sentry.cross_system_flow_review",
                "sentry.pii_log_boundary_scan",
            ],
            "remediation": "alert_only",
        },
    ),
    AgentSpec(
        agent_id="trade_guard",
        display_name="Trade Guard",
        purpose="Monitor trading safety boundaries for Financial before any paper or live trading enforcement is delegated.",
        risk_tier="T4",
        status="active",
        enabled=True,
        cadence="on_demand",
        allowed_skills=[
            "trade_guard.mode_boundary_review",
            "trade_guard.kill_switch_review",
            "trade_guard.order_path_boundary_review",
            "trade_guard.broker_credential_review",
            "notify.send",
        ],
        allowed_scopes=[
            "security.read",
            "agents.read",
            "evidence.read",
            "notify.send",
        ],
        cost_daily_cap_usd=0.0,
        approval_policy={
            "writes": "blocked",
            "remediation": "warden_approval_required",
            "trade_execution": "blocked",
        },
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "warden_managed": True,
            "warden_role": "trading_safety_monitor",
            "protected_domains": [
                "financial",
                "alpha",
                "brain",
            ],
            "monitors": [
                "paper_live_mode_boundary",
                "kill_switch_health",
                "halt_signal_health",
                "pre_trade_approval_gate",
                "spend_cap_boundary",
                "broker_credential_exposure",
                "order_execution_isolation",
            ],
            "controls": [
                "read_only_review",
                "no_order_placement",
                "no_broker_mutation",
                "warden_approval_required_for_remediation",
            ],
            "enforcement_gates": [
                "paper_mode_only_until_promoted",
                "live_mode_blocked",
                "kill_switch_must_be_open",
                "approval_bridge_must_be_healthy",
                "pre_trade_limits_must_exist",
                "no_mock_approvals_in_paper_or_live",
                "broker_order_boundary_observed",
            ],
            "capabilities": [
                "mode_boundary_review",
                "kill_switch_review",
                "order_path_boundary_review",
                "broker_credential_review",
            ],
            "planned_skills": [
                "trade_guard.mode_boundary_review",
                "trade_guard.kill_switch_review",
                "trade_guard.order_path_boundary_review",
                "trade_guard.broker_credential_review",
            ],
            "remediation": "approval_only",
            "enforcement": "planned_not_active",
            "promotion_blockers": [
                "six_month_paper_window",
                "restore_drill_and_chaos_gates",
                "operator_live_money_approval",
                "warden_authority_review",
            ],
        },
    ),
    AgentSpec(
        agent_id="tripwire",
        display_name="Tripwire",
        purpose="Monitor honeypot traps, classify suspicious hits, and escalate findings to Warden.",
        risk_tier="T1",
        status="active",
        enabled=True,
        cadence="event_driven",
        allowed_skills=["notify.send"],
        allowed_scopes=["security.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "warden_managed": True,
            "warden_role": "honeypot_sensor",
            "monitors": ["honeypot_hits", "trap_paths", "source_patterns"],
            "capabilities": [
                "source_reputation_enrichment",
                "repeated_probe_clustering",
            ],
            "remediation": "alert_only",
            "planned_skills": [
                "tripwire.source_reputation",
                "tripwire.probe_clustering",
            ],
        },
    ),
    AgentSpec(
        agent_id="ken_voice",
        display_name="Ken Voice",
        purpose="Draft in Ken's voice without autonomous sends or external side effects.",
        risk_tier="T2",
        status="planned",
        enabled=False,
        cadence="on_demand",
        allowed_skills=["imessage.read"],
        allowed_scopes=["notes.read", "imessage.read"],
        cost_daily_cap_usd=0.25,
        approval_policy={"side_effects": "blocked"},
    ),
    AgentSpec(
        agent_id="chatops_smoke",
        display_name="ChatOps Smoke",
        purpose="Post a scheduled low-risk Mattermost smoke event so the operator can trust the notification path.",
        risk_tier="T1",
        status="active",
        enabled=True,
        cadence="6h",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only"},
        metadata={
            "mattermost_channel_key": "alpha_events",
            "smoke_interval_seconds": 21600,
            "manual_run_enabled": True,
        },
    ),
    AgentSpec(
        agent_id="sweep",
        display_name="Sweep",
        purpose="Monitor UniFi WAN, switches, APs, new-device events, and network trust hardening.",
        risk_tier="T1",
        status="active",
        enabled=True,
        cadence="30s",
        allowed_skills=[
            "unifi.wan_status",
            "unifi.clients",
            "unifi.health_check",
            "notify.send",
        ],
        allowed_scopes=["network.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "alpha_events",
            "poll_interval_seconds": 30,
            "manual_run_enabled": True,
            "warden_managed": True,
            "warden_role": "network_sweep",
            "legacy_agent_id": "network_watchdog",
            "active_hardening": "service_tls_cert_renewal",
            "completed_hardenings": ["unifi_cert_pinning"],
            "cert_renewal": {
                "script": "scripts/sweep_tls_cert_renewal.py",
                "launch_label": "com.jarvis.alpha.sweep-cert-renewal.*",
                "threshold_days": 30,
            },
            "monitors": [
                "service_tls_certs",
                "unifi_tls_pin",
                "wan_health",
                "new_clients",
                "unknown_device_quarantine",
                "unifi_firmware_drift",
                "wan_failover_health",
            ],
            "active_network_checks": [
                "unifi.quarantine_recommendation",
                "unifi.firmware_drift",
                "unifi.wan_failover_health",
            ],
            "planned_skills": [
                "unifi.quarantine_recommendation",
                "unifi.firmware_drift",
                "unifi.wan_failover_health",
            ],
        },
    ),
    AgentSpec(
        agent_id="approval_canary",
        display_name="Approval Canary",
        purpose="Disabled no-op agent used only to prove SkillRunner T4 approval queue replay.",
        risk_tier="T4",
        status="active",
        enabled=False,
        cadence="manual_test_only",
        allowed_skills=["approval.canary_t4"],
        allowed_scopes=["approval.canary"],
        cost_daily_cap_usd=0.0,
        approval_policy={
            "writes": "approval_queue",
            "external_side_effects": "blocked",
        },
        metadata={
            "mattermost_channel_key": "needs_input",
            "manual_run_enabled": False,
            "canary": True,
        },
    ),
    AgentSpec(
        agent_id="internet_scout",
        display_name="Beacon Internet Scout",
        purpose="Broker current public internet evidence for Alpha chat and approved JARVIS consumers without letting web content issue instructions.",
        risk_tier="T4",
        status="active",
        enabled=True,
        cadence="on_demand",
        allowed_skills=[
            "internet_scout.search",
            "internet_scout.deep_research",
            "internet_scout.browser_task",
        ],
        allowed_scopes=[
            "internet_scout.read",
            "internet_scout.research",
            "internet_scout.consumer",
            "internet_scout.browser",
            "approval.request",
        ],
        cost_daily_cap_usd=1.0,
        approval_policy={
            "search": "T2_no_browser",
            "deep_research": "T3_cited_evidence_only",
            "browser_use": "T4_exact_approval_required",
            "memory_promotion": "review_required",
            "raw_web_content": "untrusted_data_only",
        },
        metadata={
            "mattermost_channel_key": "alpha_events",
            "manual_run_enabled": True,
            "operator_surfaces": ["health_panel", "helm_ask"],
            "evidence_store": "alpha_internet_requests",
            "gateway_owned_egress": True,
            "chat_modes": ["web_search", "deep_research"],
            "browser_runtime": "approval_queue_only",
            "prompt_injection_boundary": "web_content_is_data_not_commands",
        },
    ),
    AgentSpec(
        agent_id="inbox_watcher",
        display_name="Inbox Watcher",
        purpose="Classify inbound Gmail and surface action-worthy threads.",
        risk_tier="T2",
        status="planned",
        enabled=False,
        cadence="5m",
        allowed_skills=["gmail.search_threads", "gmail.read_thread"],
        allowed_scopes=["email.read"],
        cost_daily_cap_usd=0.50,
        approval_policy={"send": "blocked_until_wave_7"},
    ),
    AgentSpec(
        agent_id="family_concierge",
        display_name="Family Concierge",
        purpose="Route child-facing requests through age, scope, and parent-visibility controls.",
        risk_tier="T3",
        status="planned",
        enabled=False,
        cadence="per_request",
        allowed_skills=["weather.current"],
        allowed_scopes=["child.ask", "child.activity.write", "weather.read"],
        cost_daily_cap_usd=0.25,
    ),
)
