"""Initial registry catalog for the agents program.

The database migration seeds these same entries as the durable source of truth.
Keeping typed copies here gives tests and future tooling a code-native contract
before dynamic registry editing is introduced.
"""

from __future__ import annotations

from typing import Any

from brain.registry.models import AgentSpec, SkillSpec


def _skill_metadata(
    *,
    data_classification: str = "none",
    side_effect_class: str = "read",
    timeout_s: int = 30,
    retry_policy: str = "none",
    rate_limit: str = "default",
    cost_mode: str = "none",
    max_usd_per_call: float = 0.0,
    model_policy: str | None = None,
    egress_mode: str = "none",
    provider: str | None = None,
    allowed_hosts: list[str] | None = None,
    compensation: str = "not_applicable",
    test_ref: str = "tests/test_agent_skill_registry.py",
    runbook_ref: str = "docs/JARVIS_Alpha_Skills_Agents_Catalog_v0_9.md",
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the compact Skill Manifest v1 metadata block.

    Provider credentials, URLs, and secret names stay outside the manifest.
    This is governance metadata: risk, egress, runtime, cost, and audit shape.
    """

    metadata: dict[str, Any] = {
        "manifest": {
            "manifest_version": 1,
            "data_classification": data_classification,
            "side_effect_class": side_effect_class,
            "input_schema_ref": "registry://schemas/skill-input/default-v1",
            "output_schema_ref": "registry://schemas/skill-output/default-v1",
            "runtime": {
                "timeout_s": timeout_s,
                "retry_policy": retry_policy,
                "rate_limit": rate_limit,
            },
            "cost": {
                "mode": cost_mode,
                "max_usd_per_call": max_usd_per_call,
                "model_policy": model_policy,
            },
            "egress": {
                "mode": egress_mode,
                "provider": provider,
                "allowed_hosts": allowed_hosts or [],
            },
            "audit": {
                "event_name": "skill.invoke",
                "redact_fields": ["token", "secret", "body"],
            },
            "compensation": compensation,
            "test_ref": test_ref,
            "runbook_ref": runbook_ref,
        }
    }
    if extra:
        metadata.update(extra)
    return metadata


INITIAL_SKILLS: tuple[SkillSpec, ...] = (
    SkillSpec(
        name="notify.send",
        domain="notify",
        action="send",
        description="Send an Alpha notification through the primary ChatOps channel.",
        approval_tier="T2",
        scope="notify.send",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="operator_notification",
            timeout_s=10,
            retry_policy="fallback_to_pushover",
            rate_limit="60/minute/system",
            egress_mode="gateway",
            provider="mattermost",
            compensation="send_followup_correction",
            test_ref="tests/test_notify_skill.py",
            extra={
                "primary": "mattermost",
                "delivery": "incoming_webhook",
                "fallback": "pushover",
            },
        ),
    ),
    SkillSpec(
        name="notify.send_mattermost",
        domain="notify",
        action="send_mattermost",
        description="Send a Mattermost ChatOps notification through Gateway.",
        approval_tier="T2",
        scope="notify.send",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="operator_notification",
            timeout_s=10,
            retry_policy="none",
            rate_limit="60/minute/system",
            egress_mode="gateway",
            provider="mattermost",
            compensation="send_followup_correction",
            test_ref="tests/test_notify_skill.py",
            extra={
                "egress": "gateway",
                "provider": "mattermost",
                "delivery": "incoming_webhook",
                "rest_api": "phase2",
            },
        ),
    ),
    SkillSpec(
        name="notify.send_pushover",
        domain="notify",
        action="send_pushover",
        description="Send a fallback Pushover notification to Ken through Gateway.",
        approval_tier="T2",
        scope="notify.send",
        mutates_state=True,
        idempotency_required=True,
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="operator_notification",
            timeout_s=10,
            retry_policy="none",
            rate_limit="60/minute/system",
            egress_mode="gateway",
            provider="pushover",
            compensation="send_followup_correction",
            test_ref="tests/test_notify_skill.py",
            extra={"egress": "gateway", "provider": "pushover", "role": "fallback"},
        ),
    ),
    SkillSpec(
        name="unifi.wan_status",
        domain="unifi",
        action="wan_status",
        description="Read WAN status, speed, latency, and ISP state.",
        approval_tier="T1",
        scope="network.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="security",
            egress_mode="gateway",
            provider="unifi",
            rate_limit="30/minute/agent",
            test_ref="tests/test_agent_runtime_network.py",
        ),
    ),
    SkillSpec(
        name="unifi.clients",
        domain="unifi",
        action="clients",
        description="List connected UniFi clients.",
        approval_tier="T1",
        scope="network.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="security",
            egress_mode="gateway",
            provider="unifi",
            rate_limit="30/minute/agent",
            test_ref="tests/test_agent_runtime_network.py",
        ),
    ),
    SkillSpec(
        name="unifi.health_check",
        domain="unifi",
        action="health_check",
        description="Read controller, AP, and switch health signals.",
        approval_tier="T1",
        scope="network.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="security",
            egress_mode="gateway",
            provider="unifi",
            rate_limit="30/minute/agent",
            test_ref="tests/test_agent_runtime_network.py",
            extra={"adapter": "gateway_unifi"},
        ),
    ),
    SkillSpec(
        name="unifi.daughters_screentime",
        domain="unifi",
        action="daughters_screentime",
        description="Pause or resume daughters' registered devices on the home network.",
        approval_tier="T4",
        scope="network.screentime",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="child",
            side_effect_class="physical_world",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/child",
            egress_mode="gateway",
            provider="unifi",
            compensation="restore_previous_network_state",
            test_ref="tests/test_skill_policy_gate.py",
            extra={"child_profile_block": False},
        ),
    ),
    SkillSpec(
        name="weather.current",
        domain="weather",
        action="current",
        description="Read current weather conditions through Gateway's Open-Meteo adapter.",
        approval_tier="T1",
        scope="weather.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="personal",
            timeout_s=15,
            retry_policy="cache_then_transient_retry",
            rate_limit="30/minute/system",
            egress_mode="gateway",
            provider="open_meteo",
            allowed_hosts=["api.open-meteo.com"],
            test_ref="tests/test_weather_skill.py",
            extra={
                "execution_path": "skill_runner",
                "cache_ttl_seconds": 600,
                "location_policy": "configured_home_or_explicit_coordinates",
            },
        ),
    ),
    SkillSpec(
        name="gmail.search_threads",
        domain="gmail",
        action="search_threads",
        description="Search Gmail threads across configured accounts.",
        approval_tier="T1",
        scope="email.read",
        metadata=_skill_metadata(
            data_classification="personal",
            timeout_s=20,
            retry_policy="transient_retry",
            rate_limit="60/minute/account",
            egress_mode="gateway",
            provider="gmail",
            test_ref="tests/services/test_gmail_client.py",
        ),
    ),
    SkillSpec(
        name="gmail.read_thread",
        domain="gmail",
        action="read_thread",
        description="Read Gmail thread metadata and allowed body content.",
        approval_tier="T1",
        scope="email.read",
        body_access=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            timeout_s=20,
            retry_policy="transient_retry",
            rate_limit="60/minute/account",
            egress_mode="gateway",
            provider="gmail",
            test_ref="tests/services/test_gmail_client.py",
        ),
    ),
    SkillSpec(
        name="gmail.draft_reply",
        domain="gmail",
        action="draft_reply",
        description="Create a Gmail draft without sending.",
        approval_tier="T2",
        scope="email.write",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="write",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="20/minute/account",
            egress_mode="gateway",
            provider="gmail",
            compensation="delete_or_replace_draft",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="gmail.send",
        domain="gmail",
        action="send",
        description="Send Gmail to non-VIP recipients after approval.",
        approval_tier="T4",
        scope="email.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/operator",
            egress_mode="gateway",
            provider="gmail",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="gmail.send_vip",
        domain="gmail",
        action="send_vip",
        description="Send Gmail to VIP recipients under the encrypted group policy.",
        approval_tier="T1",
        scope="email.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="vip_group_policy",
            egress_mode="gateway",
            provider="gmail",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
            extra={"vip_store": "~/jarvis/.secrets/vip_groups.enc"},
        ),
    ),
    SkillSpec(
        name="imessage.read",
        domain="imessage",
        action="read",
        description="Read recent iMessage thread metadata and allowed body content.",
        approval_tier="T1",
        scope="imessage.read",
        body_access=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            timeout_s=20,
            retry_policy="transient_retry",
            rate_limit="60/minute/bridge",
            egress_mode="tailscale",
            provider="bluebubbles",
            test_ref="tests/test_agent_skill_registry.py",
        ),
    ),
    SkillSpec(
        name="imessage.send",
        domain="imessage",
        action="send",
        description="Send iMessage to non-VIP recipients after approval.",
        approval_tier="T4",
        scope="imessage.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/operator",
            egress_mode="tailscale",
            provider="bluebubbles",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="imessage.send_vip",
        domain="imessage",
        action="send_vip",
        description="Send iMessage to VIP recipients under the encrypted group policy.",
        approval_tier="T1",
        scope="imessage.send",
        mutates_state=True,
        body_access=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="message_body",
            side_effect_class="external_send",
            timeout_s=20,
            retry_policy="idempotent_retry_once",
            rate_limit="vip_group_policy",
            egress_mode="tailscale",
            provider="bluebubbles",
            compensation="send_correction_or_followup",
            test_ref="tests/test_skill_policy_gate.py",
            extra={"vip_store": "~/jarvis/.secrets/vip_groups.enc"},
        ),
    ),
    SkillSpec(
        name="smarthome.run_trusted_scene",
        domain="smarthome",
        action="run_trusted_scene",
        description="Run a trusted Home Assistant scene from the approved scene list.",
        approval_tier="T1",
        scope="smarthome.scene",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="30/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="run_inverse_scene_or_restore_state",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.run_scene",
        domain="smarthome",
        action="run_scene",
        description="Run an unknown or not-yet-trusted Home Assistant scene after approval.",
        approval_tier="T4",
        scope="smarthome.write",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="run_inverse_scene_or_restore_state",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.set_device",
        domain="smarthome",
        action="set_device",
        description="Set a direct device state through Home Assistant.",
        approval_tier="T4",
        scope="smarthome.write",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="10/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="restore_previous_device_state",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.unlock",
        domain="smarthome",
        action="unlock",
        description="Unlock a physical lock through Home Assistant.",
        approval_tier="T5",
        scope="smarthome.security",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="2/hour/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="lock_device_again_and_alert",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="smarthome.alarm_disarm",
        domain="smarthome",
        action="alarm_disarm",
        description="Disarm a home alarm panel through Home Assistant.",
        approval_tier="T5",
        scope="smarthome.security",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="physical_world",
            timeout_s=15,
            retry_policy="idempotent_retry_once",
            rate_limit="2/day/home",
            egress_mode="tailscale",
            provider="home_assistant",
            compensation="arm_alarm_again_and_alert",
            test_ref="tests/test_skill_policy_gate.py",
        ),
    ),
    SkillSpec(
        name="tasks.create",
        domain="tasks",
        action="create",
        description="Create an Obsidian Tasks markdown checkbox.",
        approval_tier="T2",
        scope="tasks.write",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="personal",
            side_effect_class="write",
            timeout_s=10,
            retry_policy="idempotent_retry_once",
            rate_limit="60/minute/operator",
            egress_mode="local",
            provider="obsidian_tasks",
            compensation="delete_or_mark_created_task_cancelled",
            test_ref="tests/test_obsidian_skills.py",
            extra={
                "execution_path": "skill_runner",
                "config_secret": "OBSIDIAN_VAULT_PATH",
                "default_path_secret": "OBSIDIAN_TASKS_INBOX",
            },
        ),
    ),
    SkillSpec(
        name="notes.search",
        domain="notes",
        action="search",
        description="Search the Obsidian vault.",
        approval_tier="T1",
        scope="notes.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="personal",
            timeout_s=10,
            retry_policy="none",
            rate_limit="120/minute/operator",
            egress_mode="local",
            provider="obsidian",
            test_ref="tests/test_obsidian_skills.py",
            extra={
                "execution_path": "skill_runner",
                "config_secret": "OBSIDIAN_VAULT_PATH",
            },
        ),
    ),
    SkillSpec(
        name="chatops.command_read",
        domain="chatops",
        action="command_read",
        description="Handle token-authenticated read-only Mattermost slash commands.",
        approval_tier="T1",
        scope="chatops.read",
        status="active",
        metadata=_skill_metadata(
            data_classification="ops",
            timeout_s=10,
            retry_policy="none",
            rate_limit="30/minute/operator",
            egress_mode="local",
            provider="mattermost",
            test_ref="tests/test_agent_events_chatops.py",
            extra={
                "surface": "mattermost",
                "write_commands": "blocked",
                "execution_path": "fastapi_route",
            },
        ),
    ),
    SkillSpec(
        name="approval.canary_t4",
        domain="approval",
        action="canary_t4",
        description="No-op T4 canary for proving SkillRunner approval queue replay.",
        approval_tier="T4",
        scope="approval.canary",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="ops",
            side_effect_class="control_plane",
            timeout_s=5,
            retry_policy="idempotent_retry_once",
            rate_limit="5/day/operator",
            egress_mode="none",
            provider=None,
            compensation="not_applicable_no_external_side_effect",
            test_ref="tests/test_approval_canary_skill.py",
            extra={
                "execution_path": "skill_runner",
                "approval_queue_bridge": "enabled",
                "canary": True,
            },
        ),
    ),
    SkillSpec(
        name="secrets.rotate",
        domain="secrets",
        action="rotate",
        description="Rotate approved Alpha secrets and service credentials through the Keyturner workflow.",
        approval_tier="T4",
        scope="secrets.rotate",
        status="active",
        mutates_state=True,
        idempotency_required=True,
        metadata=_skill_metadata(
            data_classification="security",
            side_effect_class="control_plane",
            timeout_s=600,
            retry_policy="checkpointed_rollback",
            rate_limit="10/day/operator",
            egress_mode="tailscale",
            provider="alpha_control_plane",
            compensation="restore_previous_secret_and_restart_services",
            test_ref="tests/test_agent_skill_registry.py",
            extra={
                "execution_path": "skill_runner",
                "approval_queue_bridge": "enabled",
                "approval_required": True,
                "actuator": "gateway_rotation_proxy",
                "handled_secret_classes": [
                    "api_key",
                    "service_token",
                    "admin_pin",
                    "db_password",
                ],
            },
        ),
    ),
)


INITIAL_AGENTS: tuple[AgentSpec, ...] = (
    AgentSpec(
        agent_id="buddy",
        display_name="Buddy",
        purpose="Maintain memory, surface operational events, and perform low-risk housekeeping.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="60s",
        launch_label="com.jarvis.alpha.buddy",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["memory.write", "buddy.events.write", "notify.send"],
        cost_daily_cap_usd=0.0,
        metadata={"mattermost_channel_key": "alpha_events"},
    ),
    AgentSpec(
        agent_id="dream_mode",
        display_name="Dream Mode",
        purpose="Plan, review, and execute bounded overnight work through Temporal.",
        risk_tier="T4",
        status="active",
        enabled=True,
        cadence="on_demand",
        launch_label="com.jarvis.alpha.temporal.worker",
        allowed_skills=["notes.search", "notify.send", "tasks.create"],
        allowed_scopes=[
            "dream.execute",
            "approval.request",
            "notes.read",
            "notify.send",
            "tasks.write",
        ],
        cost_daily_cap_usd=1.0,
        approval_policy={"writes": "approval_queue", "allowlist_only": True},
        metadata={"mattermost_channel_key": "alpha_events"},
    ),
    AgentSpec(
        agent_id="approval_triage",
        display_name="Approval Triage",
        purpose="Surface approval queue events and operator decisions into ChatOps.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="event_driven",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["approval.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "blocked"},
        metadata={"mattermost_channel_key": "needs_input"},
    ),
    AgentSpec(
        agent_id="watchdog",
        display_name="Watchdog",
        purpose="Surface infrastructure health degradation and restoration events.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="60s",
        launch_label="com.jarvis.alpha.watchdog",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["notify.send", "watchdog.events.ingest"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "blocked"},
        metadata={"mattermost_channel_key": "alerts"},
    ),
    AgentSpec(
        agent_id="porchlight",
        display_name="Porchlight",
        purpose="Run scheduled security posture sweeps and surface dangerous findings.",
        risk_tier="T2",
        status="active",
        enabled=True,
        cadence="daily",
        launch_label="com.jarvis.alpha.porchlight",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["notify.send", "security.read"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "security_alerts",
            "report_path": "logs/porchlight_security_report.json",
            "manual_run_enabled": True,
        },
    ),
    AgentSpec(
        agent_id="keyturner",
        display_name="Keyturner",
        purpose="Own approved Alpha key and password rotations across existing rotation jobs.",
        risk_tier="T4",
        status="active",
        enabled=True,
        cadence="on_demand",
        allowed_skills=["secrets.rotate", "notify.send"],
        allowed_scopes=["secrets.rotate", "notify.send", "security.read"],
        cost_daily_cap_usd=0.0,
        approval_policy={
            "writes": "approval_required",
            "api_keys": "T3",
            "service_tokens": "T3",
            "db_passwords": "T4",
            "rollback": "required",
        },
        metadata={
            "mattermost_channel_key": "security_alerts",
            "manual_run_enabled": False,
            "rotation_config": "scripts/secrets_rotation.json",
            "existing_actuators": [
                "scripts/rotate_secret.py",
                "scripts/rotate_service_token.py",
                "launchagents/com.jarvis.alpha.rotate.*",
            ],
            "porchlight_relationship": "porchlight_detects_keyturner_remediates",
        },
    ),
    AgentSpec(
        agent_id="ken_voice",
        display_name="Ken Voice",
        purpose="Draft in Ken's voice without autonomous sends or external side effects.",
        risk_tier="T2",
        status="planned",
        enabled=False,
        cadence="on_demand",
        allowed_scopes=["notes.read"],
        cost_daily_cap_usd=0.25,
        approval_policy={"side_effects": "blocked"},
    ),
    AgentSpec(
        agent_id="chatops_smoke",
        display_name="ChatOps Smoke",
        purpose="Post a scheduled low-risk Mattermost smoke event so the operator can trust the notification path.",
        risk_tier="T1",
        status="active",
        enabled=True,
        cadence="6h",
        allowed_skills=[
            "notify.send",
            "notify.send_mattermost",
            "notify.send_pushover",
        ],
        allowed_scopes=["notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only"},
        metadata={
            "mattermost_channel_key": "alpha_events",
            "smoke_interval_seconds": 21600,
            "manual_run_enabled": True,
        },
    ),
    AgentSpec(
        agent_id="network_watchdog",
        display_name="Network Watchdog",
        purpose="Monitor UniFi WAN, switches, APs, and new-device events.",
        risk_tier="T1",
        status="active",
        enabled=False,
        cadence="30s",
        allowed_skills=[
            "unifi.wan_status",
            "unifi.clients",
            "unifi.health_check",
            "notify.send",
        ],
        allowed_scopes=["network.read", "notify.send"],
        cost_daily_cap_usd=0.0,
        approval_policy={"writes": "notification_only", "remediation": "blocked"},
        metadata={
            "mattermost_channel_key": "alpha_events",
            "poll_interval_seconds": 30,
            "manual_run_enabled": True,
        },
    ),
    AgentSpec(
        agent_id="approval_canary",
        display_name="Approval Canary",
        purpose="Disabled no-op agent used only to prove SkillRunner T4 approval queue replay.",
        risk_tier="T4",
        status="active",
        enabled=False,
        cadence="manual_test_only",
        allowed_skills=["approval.canary_t4"],
        allowed_scopes=["approval.canary"],
        cost_daily_cap_usd=0.0,
        approval_policy={
            "writes": "approval_queue",
            "external_side_effects": "blocked",
        },
        metadata={
            "mattermost_channel_key": "needs_input",
            "manual_run_enabled": False,
            "canary": True,
        },
    ),
    AgentSpec(
        agent_id="inbox_watcher",
        display_name="Inbox Watcher",
        purpose="Classify inbound Gmail and surface action-worthy threads.",
        risk_tier="T2",
        status="planned",
        enabled=False,
        cadence="5m",
        allowed_skills=["gmail.search_threads", "gmail.read_thread"],
        allowed_scopes=["email.read"],
        cost_daily_cap_usd=0.50,
        approval_policy={"send": "blocked_until_wave_7"},
    ),
    AgentSpec(
        agent_id="family_concierge",
        display_name="Family Concierge",
        purpose="Route child-facing requests through age, scope, and parent-visibility controls.",
        risk_tier="T3",
        status="planned",
        enabled=False,
        cadence="per_request",
        allowed_skills=["weather.current"],
        allowed_scopes=["child.ask", "child.activity.write", "weather.read"],
        cost_daily_cap_usd=0.25,
    ),
)
