#!/usr/bin/env python3
"""
Handoff scaffold generator for session close.

Reads the same JSON manifest as gh_sync.py. Produces a markdown handoff
file with auto-populated shipped items, TD tables, commit range, and
placeholder sections for narrative.

Usage:
    python3 handoff_scaffold.py --manifest manifests/2026-04-18.json
    python3 handoff_scaffold.py --manifest manifests/2026-04-18.json --output custom/path.md

Default output: docs/handoffs/HANDOFF_<session_date>_<session_sequence>.md

Will NOT overwrite existing files — bails with error.
"""

import argparse
import json
import sys
from pathlib import Path


def load_manifest(path: Path) -> dict:
    if not path.exists():
        print(f"❌ Manifest not found: {path}", file=sys.stderr)
        sys.exit(2)
    try:
        with open(path) as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f"❌ Manifest JSON invalid: {e}", file=sys.stderr)
        sys.exit(2)


def build_shipped_table(manifest: dict) -> str:
    """Build a table of shipped TDs from close_existing + create_and_close."""
    rows = ["| TD | Title | Closing Commit |", "|---|---|---|"]
    for item in manifest.get("close_existing", []):
        td = item["td_id"]
        commit = item.get("comment", "")
        # Extract first commit hash-like token from comment
        import re

        match = re.search(r"\b([0-9a-f]{7,40})\b", commit)
        hash_str = match.group(1) if match else "—"
        rows.append(f"| {td} | (existing issue closed) | `{hash_str}` |")
    for item in manifest.get("create_and_close", []):
        td = item["td_id"]
        commit = item.get("close_comment", "")
        import re

        match = re.search(r"\b([0-9a-f]{7,40})\b", commit)
        hash_str = match.group(1) if match else "—"
        title = item.get("title", "").replace(f"{td}: ", "")
        rows.append(f"| {td} | {title[:60]} | `{hash_str}` |")
    return "\n".join(rows)


def build_new_tds_table(manifest: dict) -> str:
    """Build a table of newly-logged TDs from create_open."""
    rows = ["| TD | Title | Labels |", "|---|---|---|"]
    for item in manifest.get("create_open", []):
        td = item["td_id"]
        title = item.get("title", "").replace(f"{td}: ", "")
        labels = ", ".join(item.get("labels", []))
        rows.append(f"| {td} | {title[:70]} | {labels} |")
    return "\n".join(rows)


def build_scaffold(manifest: dict) -> str:
    session_date = manifest["session_date"]
    session_seq = manifest.get("session_sequence", "01")
    commit_range = manifest.get("session_commit_range", {})
    from_hash = commit_range.get("from", "UNKNOWN")
    to_hash = commit_range.get("to", "UNKNOWN")

    shipped_count = len(manifest.get("close_existing", [])) + len(
        manifest.get("create_and_close", [])
    )
    new_td_count = len(manifest.get("create_open", []))

    handoff_data = manifest.get("handoff", {})
    tldr = handoff_data.get("tldr", "<< ADD TL;DR HERE >>")
    arch_decisions = handoff_data.get("architecture_decisions", [])
    next_entry = handoff_data.get(
        "next_session_entry", "<< ADD NEXT SESSION ENTRY POINT >>"
    )
    lessons = handoff_data.get("lessons_learned", [])

    arch_section = ""
    if arch_decisions:
        arch_section = "\n\n".join(
            f"### {d.get('title', 'Untitled')}\n\n{d.get('description', '<< description >>')}"
            for d in arch_decisions
        )
    else:
        arch_section = "<< ADD ARCHITECTURE DECISIONS HERE >>"

    lessons_section = ""
    if lessons:
        lessons_section = "\n".join(f"- {lesson}" for lesson in lessons)
    else:
        lessons_section = "<< ADD LESSONS LEARNED HERE >>"

    scaffold = f"""# HANDOFF {session_date}_{session_seq}

**Commit range:** `{from_hash}` → `{to_hash}`
**Items shipped:** {shipped_count}
**New TDs logged:** {new_td_count}

---

## TL;DR

{tldr}

---

## What Shipped

{build_shipped_table(manifest)}

---

## New TDs Logged

{build_new_tds_table(manifest)}

---

## Architecture Decisions

{arch_section}

---

## Lessons Learned

{lessons_section}

---

## Cluster State At Close

<< ADD: all nodes at `{to_hash}`, tests 133/133, cluster healthy >>

---

## Next Session — Entry Point

{next_entry}

---

## Related Docs

- State review: `docs/state/STATE_{session_date}.md` (if exists)
- Phase status: `docs/JARVIS_Alpha_Phase_Status.md`
- Architecture: `docs/JARVIS_Alpha_Architecture_Review_V1.md` (marked SUPERSEDED — full V2 post-D3 as TD-99)

---

*Generated by handoff_scaffold.py from `scripts/session_close/manifests/{session_date}.json`. Enhance sections marked `<<` with narrative before committing.*
"""
    return scaffold


def main():
    parser = argparse.ArgumentParser(description="Handoff scaffold generator")
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    session_date = manifest["session_date"]
    session_seq = manifest.get("session_sequence", "01")

    if args.output:
        output_path = args.output
    else:
        output_path = Path(f"docs/handoffs/HANDOFF_{session_date}_{session_seq}.md")

    if output_path.exists():
        print(f"❌ Refusing to overwrite: {output_path}", file=sys.stderr)
        print("   Use --output to choose a different path.", file=sys.stderr)
        sys.exit(1)

    scaffold = build_scaffold(manifest)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(scaffold)

    print(f"✅ Scaffold written: {output_path}")
    print("   Next: enhance sections marked `<<` with narrative")


if __name__ == "__main__":
    main()
